project:
  type: book

book:
  title: "Stats & ML Notes"
  author: "Kittipos Sirivongrungson"
  date: "4/16/2022" # `today` for current date when render
  site-url: https://r-stats-lightbridge.netlify.app
  repo-url: https://github.com/Lightbridge-KS/r-stats-notes
  chapters:
    - index.qmd
    - part: "Inferential Stats"
      chapters:
      - "stats/normality-test.qmd"
      - "stats/infer.qmd"
    - part: "Compare group"
      chapters:
      - "stats/wilcoxon.qmd"
    - part: "Sample Size"
      chapters: 
        - "stats/sam-size.qmd"
        - "stats/sam-size-2.qmd"
    - part: "Causal"
      chapters: 
        - "stats/causal-dag.qmd"
        - "stats/causal-malaria.qmd"
    - part: "Diagnostic Study"
      chapters:
      - "stats/dta.qmd"
      - "stats/dta-yardstick.qmd"
      - "stats/perf-mat.qmd"
    - part: "Correlation"
      chapters:
      - "stats/cor-icc.qmd"
    - part: "Feature Eng"
      chapters: 
      - "ml/bestglm.qmd"
    - part: "ML"
      chapters: 
      - "ml/tidymod-overview.qmd"
      - "ml/ml-ops.qmd"
      - "ml/compare-mod.qmd"
      - "ml/tune-mod.qmd"
    - part: "Performace"
      chapters:
      - "misc/parallel.qmd"
    - part: "Misc"
      chapters:
      - "misc/de-iden.qmd"
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: zephyr #cosmo
      dark: superhero
    number-sections: false
    toc: true
    toc-depth: 4
  #pdf:
    #documentclass: scrreprt


# freeze computational output ? (see: https://quarto.org/docs/projects/code-execution.html#freeze)
freeze: auto



