---
title: "Inter-rator"
---

```{r setup, include=FALSE}
here::i_am("stats/cor-icc.qmd")
library(here)
library(tidyverse)
```

```{r}
library(irr)
library(yardstick)
```

- [Inter-rater reliability](https://www.andywills.info/rminr/irr.html)

- [DataNovia](https://www.datanovia.com/en/lessons/inter-rater-reliability-analyses-quick-r-codes/)

## Cohen Kappa

```{r}
# Diagnoses data
data("diagnoses", package = "irr")
diagnoses
```

### Plot

```{r}
cm_r1r2 <- conf_mat(diagnoses, truth = rater1, estimate = rater2)
autoplot(cm_r1r2, type = "heatmap")
```

### Calculate Cohen’s kappa
 
The Cohen’s kappa corresponds to the unweighted kappa. It can be used for two nominal or two ordinal categorical variables


```{r}
diagnoses |> 
  select(rater1, rater2) |> 
  kappa2(weight = "unweighted")
```


## Intraclass correlation coefficient (ICC)

### DataNovia

```{r}
data("anxiety", package = "irr")
head(anxiety, 4)
```


```{r}
icc(
  anxiety, model = "twoway", 
  type = "agreement", unit = "single"
  )
```


### Radiomics Example

```{r}
# Simulated radiomics features data for 5 subjects and 2 observers
radiomics_data <- data.frame(
  Subject = 1:5,
  Observer1_Feature1 = c(0.75, 0.82, 0.91, 0.85, 0.88),
  Observer2_Feature1 = c(0.73, 0.83, 0.89, 0.86, 0.87),
  Observer1_Feature2 = c(100, 102, 105, 108, 107),
  Observer2_Feature2 = c(99, 101, 104, 109, 106)
)

radiomics_data
```


```{r}
# ICC for Feature 1 across both observers
feature1_data <- radiomics_data[, c("Observer1_Feature1", "Observer2_Feature1")]
icc_feature1 <- icc(feature1_data, 
                    model = "twoway", 
                    type = "agreement", 
                    unit = "single")

icc_feature1
```

```{r}
radiomics_data |> 
  ggplot(aes(Observer1_Feature1, Observer2_Feature1)) +
  geom_point() + 
  geom_smooth(method = "lm")
```



